---
sidebar: sidebar 
permalink: ontap-security-hardening/data-replication-encryption.html 
keywords: tr-4569, ontap hardening guide, encrypted SnapMirror, SnapVault, FlexCache, pre-shared key, TLS 1.2, TLS 1.3, TLS 
summary: データレプリケーション暗号化を使用して、ONTAPクラスタ間で事前共有鍵を使用したSnapMirror、SnapVault、FlexCacheのレプリケーショントラフィックをTLS暗号化します。 
---
= データレプリケーションの暗号化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保存データの暗号化を補うために、SnapMirror、SnapVault、またはFlexCacheの事前共有キーを使用したTLSによるクラスタ間のONTAPデータレプリケーショントラフィックを暗号化できます。

ディザスタリカバリ、キャッシュ、またはバックアップのためにデータをレプリケートする場合は、ONTAPクラスタ間でネットワークを介して転送するときに、そのデータを保護する必要があります。これにより、転送中の機密データに対する悪意のある中間者攻撃を防ぐことができます。

ONTAP 9.6以降、クラスタピアリング暗号化により、SnapMirror、SnapVault、FlexCacheなどのONTAPデータレプリケーション機能に対してTLS 1.2 AES-256 GCM暗号化がサポートされます。暗号化は、2つのクラスタピア間の事前共有キー（PSK）によって設定されます。

ONTAP 9.15.1以降、クラスタピアリング暗号化により、SnapMirror、SnapVault、FlexCacheなどのONTAPデータレプリケーション機能に対してTLS 1.3 AES-256 GCM暗号化がサポートされます。暗号化は、2つのクラスタピア間の事前共有キー（PSK）によってセットアップされます。

NSE、NVE、NAEなどの技術を使用して保存データを保護しているお客様は、ONTAP 9.6以降にアップグレードしてクラスタピアリング暗号化を使用することで、エンドツーエンドのデータ暗号化も使用できます。

クラスター ピアリングは、クラスター ピア間のすべてのデータを暗号化します。例えば、SnapMirrorを使用する場合、すべてのピアリング情報とソースとデスティネーション クラスタ ピア間のすべてのSnapMirror関係が暗号化されます。クラスタ ピアリング暗号化が有効になっているクラスタ ピア間でクリアテキスト データを送信することはできません。

ONTAP 9.6 以降では、新しいクラスタピア関係ではデフォルトで暗号化が有効になっています。ONTAP 9.6 より前に作成されたクラスタピア関係で暗号化を有効にするには、ソースクラスタとデスティネーション クラスタを 9.6 にアップグレードする必要があります。さらに、 `cluster peer modify`コマンドを使用して、ソースクラスタピアとデスティネーション クラスタピアの両方がクラスタピアリング暗号化を使用するように変更する必要があります。

ONTAP 9.6では、次の例に示すように、既存のピア関係をクラスタピアリング暗号化を使用するように変換できます：

[listing]
----
On the destination cluster peer:

cluster2::> cluster peer modify cluster1 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter a passphrase.

On the source cluster peer:

cluster1::> cluster peer modify cluster2 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter the same passphrase you created in the previous step.
----