---
sidebar: sidebar 
keywords: Databases, Applications, Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: apps-dbs.html 
summary: これらのテクニカルレポートには、ONTAP上のアプリケーションとデータベースの概要と推奨されるプラクティスが記載されています 
---
= アプリケーションおよびデータベースのテクニカルレポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAPは、多くのエンタープライズアプリケーションやデータベーステクノロジのデータ管理とデータ保護の基盤です。次のテクニカルレポートでは、Microsoft SQL Server、MySQL、Oracle、PostgreSQL、SAP HANAに対するNetAppの推奨プラクティスと実装手順について説明します。



== Microsoft SQL Server の場合

SQL ServerはMicrosoftのデータプラットフォームの基盤であり、オンプレミスでもクラウドでも、インメモリテクノロジを使用してミッションクリティカルなパフォーマンスを実現し、あらゆるデータの分析を高速化します。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/mssql/overview.html["ONTAPを使用したMicrosoft SQL Serverのベストプラクティス"]
ストレージ管理者およびデータベース管理者がMicrosoft SQL ServerをONTAPストレージに正常に導入する方法について説明します。


NOTE: このドキュメントは、以前に公開されたテクニカルレポート（TR-4590：『Best Practice Guide for Microsoft SQL Server with ONTAP』）に代わるものです。_

link:https://www.netapp.com/pdf.html?item=/media/88704-tr-4976-virtualized-microsoft-sql-server-performance-on-netapp-aff-a-series-and-c-series.pdf["TR-4976：『Virtualized Microsoft SQL Server performance on NetApp AFF A-Series and C-Series systems』"^]
NetApp AFF AシリーズおよびCシリーズシステムを使用したMicrosoft SQL Serverのパフォーマンス特性と、ワークロードに基づいて適切なシステムを選択する方法について説明します。

link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714：『Best Practices for Microsoft SQL Server using SnapCenter』"^]
SnapCenterテクノロジを使用してONTAPストレージにMicrosoft SQL Serverを適切に導入し、データを保護する方法をご紹介します。



== MySQL

このドキュメントでは、ONTAPにMySQLを導入するための構成要件と、調整とストレージ構成に関するガイダンスを提供します。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/mysql/overview.html["NetApp ONTAP上のMySQLデータベースのベストプラクティス"]
MySQLとその派生であるMariaDBやPerconaなどは、多くのエンタープライズアプリケーションで広く使用されています。これらのアプリケーションは、グローバルなソーシャルネットワーキングサイトや大規模なeコマースシステムから、数千ものデータベースインスタンスを含むSMBホスティングシステムまで多岐にわたります。ONTAPにMySQLを導入するための調整とストレージ構成に関する要件とガイダンスについて説明します。


NOTE: 本ドキュメントは、以前に公開されたテクニカルレポート（TR-4722）『MySQL database on NetApp ONTAP best practices』に代わるものです。_



== Oracle の場合

ONTAPはOracleデータベース向けに設計されています。ONTAPは数十年にわたり、リレーショナルデータベースI/O固有の要求に合わせて最適化されてきました。また、Oracleデータベースのニーズに対応するために、さらにはOracle Inc自体の要求にも対応するために、複数のONTAP機能が開発されました。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/overview.html["ONTAP上のOracleデータベース"]
ストレージ管理者およびデータベース管理者がONTAPストレージにOracleを正常に導入するための推奨事項について説明します。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/dp/oracle-data-protection-introduction.html["ONTAPによるOracleデータ保護"]
ストレージ管理者およびデータベース管理者は、ONTAPストレージ上のOracleに対して、バックアップ、リカバリ、複製、ディザスタリカバリを正常に実行できるようにするための推奨されるプラクティスについて説明します。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/dr/oracle-dr-overview.html["ONTAPによるOracle向けディザスタリカバリ"]
MetroClusterおよびSnapMirrorビジネス継続性を使用してOracleデータベースを運用する場合の推奨事項、テスト手順、およびその他の考慮事項について説明します。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/migration/oracle-migration-overview.html["ONTAPストレージシステムへのOracleデータベースの移行"]
移行戦略を計画する際の全体的な考慮事項、データ移動を行う3つの異なるレベル、使用可能なさまざまな手順の詳細について説明します。


NOTE: 以前に公開されていたテクニカルレポート（TR-3633：『Oracle databases on ONTAP』、TR-4591：『Oracle data protection：backup、recovery、replication』、TR-4592：『Oracle on MetroCluster』、TR-4534：『Migration of Oracle databases to NetApp storage systems_

link:https://www.netapp.com/pdf.html?item=/media/85630-tr-4969.pdf["TR-4969：『Oracle database performance on AFF A-Series and C-Series』"^]
ONTAPは、インライン圧縮、ハードウェアの無停止アップグレード、外部ストレージアレイからのLUNインポートなどの機能を標準搭載した強力なデータ管理プラットフォームです。最大24ノードのクラスタ構成が可能で、Network File System（NFS）、Server Message Block（SMB；サーバメッセージブロック）、iSCSI、Fibre Channel（FC；ファイバチャネル）、Nonvolatile Memory Express（NVMe）の各プロトコルを通じてデータを同時に提供できます。さらに、Snapshotテクノロジは、数万個のオンラインバックアップと完全に運用可能なデータベースクローンを作成するための基盤となります。ONTAPの豊富な機能セットに加えて、データベースのサイズ、パフォーマンス要件、データ保護のニーズなど、ユーザにはさまざまな要件があります。AFFストレージシステム（AシリーズとCシリーズの両方を含む）を使用したベアメタルデータベースのパフォーマンスについて説明し、2つのAFFオプションの最大値と実際の違いについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/85629-tr-4971.pdf["TR-4971：『Virtualized Oracle database performance on AFF A-Series and C-Series』"^]
ONTAPは、インライン圧縮、ハードウェアの無停止アップグレード、外部ストレージアレイからのLUNインポートなどの機能を標準搭載した強力なデータ管理プラットフォームです。最大24ノードのクラスタ構成が可能で、Network File System（NFS）、Server Message Block（SMB；サーバメッセージブロック）、iSCSI、Fibre Channel（FC；ファイバチャネル）、Nonvolatile Memory Express（NVMe）の各プロトコルを通じてデータを同時に提供できます。さらに、Snapshotテクノロジは、数万個のオンラインバックアップと完全に運用可能なデータベースクローンを作成するための基盤となります。ONTAPの豊富な機能セットに加えて、データベースのサイズ、パフォーマンス要件、データ保護のニーズなど、ユーザにはさまざまな要件があります。AFFストレージシステム（AシリーズとCシリーズの両方を含む）を使用した仮想データベースのパフォーマンスについて説明し、最大値と2つのAFFオプションの実際の違いについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/9138-tr4695.pdf["TR-4695：『Database storage tiering with FabricPool』"^]
Oracle Relational Database Management System（RDBMS）など、さまざまなデータベースを使用するFabricPoolのメリットと構成オプションについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/40384-tr-4899.pdf["TR-4899：『Oracle Database transparent application failover with SnapMirror Business Continuity』"^]
SnapMirrorビジネス継続性（SM-BC）とOracle Real Application Cluster（RAC）は、透過的なアプリケーションフェイルオーバー（TAF）と、サイト障害や実際の災害が発生した場合の継続性を提供します。SM-BCをOracle RACのストレージコンポーネントとして使用するAFFストレージアレイの構成ガイダンスと推奨事項について説明します。

link:https://www.netapp.com/pdf.html?item=/media/21901-tr-4876.pdf["TR-4876：『Oracle multitenancy with ONTAP 解決策and deployment best practices』"^]
ONTAPストレージを使用してOracleマルチテナントデータベースをプロビジョニング、管理、保護し、OracleマルチテナントデータベースとONTAPソフトウェアの機能の両方のメリットを最大限に活用する方法について、解決策が推奨するプラクティスを紹介します。



== PostgreSQL

PostgreSQLには、PostgreSQL、PostgreSQL Plus、EDB Postgres Advanced Server（EPAS）などのバリアントが付属しています。PostgreSQLは通常、多層アプリケーションのバックエンドデータベースとして導入されます。NetApp ONTAPは、信頼性、パフォーマンス、効率に優れたデータ管理機能を備えたPostgreSQLデータベースを実行するための優れた選択肢です。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/postgres/overview.html["ONTAP上のPostgreSQLデータベースのベストプラクティス"]
PostgreSQLには、PostgreSQL、PostgreSQL Plus、EDB Postgres Advanced Server（EPAS）などのバリアントが付属しています。PostgreSQLは通常、多層アプリケーションのバックエンドデータベースとして導入されます。一般的なミドルウェアパッケージ(PHP、Java、Python、Tcl/Tk、ODBCなど)でサポートされています。 とJDBC）は、オープンソースのデータベース管理システムでは、歴史的に人気のある選択肢でした。ONTAPにPostgreSQLを導入するためのチューニングとストレージ構成に関する設定要件とガイダンスについて説明します。


NOTE: このドキュメントは、以前に公開されていたテクニカルレポートTR-4770：『PostgreSQL database on ONTAP best practices』に代わるものです。



== SAP HANA のサポート

SAPソリューションの構成、管理、自動化に関するベストプラクティスについては、NetAppのSAPソリューションページを参照してください。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/["ONTAP上のSAP HANAデータベースソリューション"]
