---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: apps-dbs.html 
summary: これらのテクニカルレポートには、ONTAP上のアプリケーションとデータベースの概要と推奨されるプラクティスが記載されています 
---
= アプリケーションおよびデータベースのテクニカルレポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAPは、多くのエンタープライズアプリケーションやデータベーステクノロジのデータ管理とデータ保護の基盤です。次のテクニカルレポートでは、Microsoft SQL Server、MySQL、Oracle、およびPostgreSQLのNetApp推奨プラクティスと実装手順について説明します。



== Microsoft SQL Server の場合

link:https://www.netapp.com/pdf.html?item=/media/8585-tr4590.pdf["TR-4590：『Best Practice Guide for Microsoft SQL Server with ONTAP』"^]
ストレージ管理者およびデータベース管理者がMicrosoft SQL ServerをONTAPストレージに正常に導入する方法について説明します。

link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714：『Best Practices for Microsoft SQL Server using SnapCenter』"^]
SnapCenterテクノロジを使用してONTAPストレージにMicrosoft SQL Serverを適切に導入し、データを保護する方法をご紹介します。



== MySQL

link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf["ONTAP上のMySQLデータベース"^]
MySQLとその派生であるMariaDBやPerconaなどは、多くのエンタープライズアプリケーションで広く使用されています。これらのアプリケーションは、グローバルなソーシャルネットワーキングサイトや大規模なeコマースシステムから、数千ものデータベースインスタンスを含むSMBホスティングシステムまで多岐にわたります。ONTAPにMySQLを導入するための調整とストレージ構成に関する要件とガイダンスについて説明します。



== Oracle の場合

link:https://www.netapp.com/pdf.html?item=/media/8744-tr3633pdf.pdf["TR-3633：『ONTAP 上のOracleデータベース』"^]
ストレージ管理者およびデータベース管理者がONTAPストレージにOracleを正常に導入するための推奨事項について説明します。

link:https://www.netapp.com/pdf.html?item=/media/85630-tr-4969.pdf["TR-4969：『Oracle Database Performance on AFF A-Series and C-Series』"^]
ONTAPは、インライン圧縮、ハードウェアの無停止アップグレード、外部ストレージアレイからのLUNインポートなどの機能を標準搭載した強力なデータ管理プラットフォームです。最大24ノードのクラスタ構成が可能で、Network File System（NFS）、Server Message Block（SMB；サーバメッセージブロック）、iSCSI、Fibre Channel（FC；ファイバチャネル）、Nonvolatile Memory Express（NVMe）の各プロトコルを通じてデータを同時に提供できます。さらに、Snapshotテクノロジは、数万個のオンラインバックアップと完全に運用可能なデータベースクローンを作成するための基盤となります。ONTAPの豊富な機能セットに加えて、データベースのサイズ、パフォーマンス要件、データ保護のニーズなど、ユーザにはさまざまな要件があります。AFFストレージシステム（AシリーズとCシリーズの両方を含む）を使用したベアメタルデータベースのパフォーマンスについて説明し、2つのAFFオプションの最大値と実際の違いについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/85629-tr-4971.pdf["TR-4971：『Virtualized Oracle database performance on AFF A-Series and C-Series』"^]
ONTAPは、インライン圧縮、ハードウェアの無停止アップグレード、外部ストレージアレイからのLUNインポートなどの機能を標準搭載した強力なデータ管理プラットフォームです。最大24ノードのクラスタ構成が可能で、Network File System（NFS）、Server Message Block（SMB；サーバメッセージブロック）、iSCSI、Fibre Channel FC（ファイバチャネルFC）、Nonvolatile Memory Express（NVMe）の各プロトコルを通じてデータを同時に提供できます。さらに、Snapshotテクノロジは、数万個のオンラインバックアップと完全に運用可能なデータベースクローンを作成するための基盤となります。ONTAPの豊富な機能セットに加えて、データベースのサイズ、パフォーマンス要件、データ保護のニーズなど、ユーザにはさまざまな要件があります。AFFストレージシステム（AシリーズとCシリーズの両方を含む）を使用した仮想データベースのパフォーマンスについて説明し、最大値と2つのAFFオプションの実際の違いについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/19666-tr-4591.pdf["TR-4591：『Oracle data protection：Backup、recovery、replication、and disaster recovery』"^]
ストレージ管理者およびデータベース管理者は、ONTAPストレージ上のOracleに対して、バックアップ、リカバリ、複製、ディザスタリカバリを正常に実行できるようにするための推奨されるプラクティスについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/8583-tr4592.pdf["TR-4592：『Oracle on MetroCluster』"^]
MetroCluster同期レプリケーション機能でOracleデータベースを運用する場合の推奨事項、テスト手順、およびその他の考慮事項について説明します。

link:https://www.netapp.com/pdf.html?item=/media/19750-tr-4534.pdf["TR-4534：『Migration of Oracle Databases to ONTAP Storage Systems』"^]
移行戦略を計画する際の全体的な考慮事項、データ移動を行う3つの異なるレベル、使用可能なさまざまな手順の詳細について説明します。

link:https://www.netapp.com/pdf.html?item=/media/9138-tr4695.pdf["TR-4695：『Database storage tiering with FabricPool』"^]
Oracle Relational Database Management System（RDBMS）など、さまざまなデータベースを使用するFabricPoolのメリットと構成オプションについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/40384-tr-4899.pdf["TR-4899：『Oracle Database transparent application failover with SnapMirror Business Continuity』"^]
SnapMirrorビジネス継続性（SM-BC）とOracle Real Application Cluster（RAC）は、透過的なアプリケーションフェイルオーバー（TAF）と、サイト障害や実際の災害が発生した場合の継続性を提供します。SM-BCをOracle RACのストレージコンポーネントとして使用するAFFストレージアレイの構成ガイダンスと推奨事項について説明します。

link:https://www.netapp.com/pdf.html?item=/media/21901-tr-4876.pdf["TR-4876：『Oracle multitenancy with ONTAP 解決策and deployment best practices』"^]
ONTAPストレージを使用してOracleマルチテナントデータベースをプロビジョニング、管理、保護し、OracleマルチテナントデータベースとONTAPソフトウェアの機能の両方のメリットを最大限に活用する方法について、解決策が推奨するプラクティスを紹介します。



== PostgreSQL

link:https://www.netapp.com/pdf.html?item=/media/17140-tr4770.pdf["TR-4770：『PostgreSQL database on ONTAP』"^]
PostgreSQLには、PostgreSQL、PostgreSQL Plus、EDB Postgres Advanced Server（EPAS）などのバリアントが付属しています。PostgreSQLは通常、多層アプリケーションのバックエンドデータベースとして導入されます。一般的なミドルウェアパッケージ(PHP、Java、Python、Tcl/Tk、ODBCなど)でサポートされています。 とJDBC）は、オープンソースのデータベース管理システムでは、歴史的に人気のある選択肢でした。ONTAPにPostgreSQLを導入するためのチューニングとストレージ構成に関する設定要件とガイダンスについて説明します。



== SAP HANA のサポート

link:https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_introduction.html["TR-4435：『SAP HANA on NetApp AFF Systems with NFS』"]
NFSを使用するAFFシステムでSAP HANAを運用する際の推奨事項や考慮事項について説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_fc_introduction.html["TR-4436 ：『 SAP HANA on NetApp AFF Systems with Fibre Channel Protocol 』"]
ファイバチャネルを使用するAFFシステムでSAP HANAを運用する際の推奨事項や考慮事項について説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana-fas-nfs_introduction.html["TR-4290：『SAP HANA on NetApp FAS systems with NFS』"]
NFSを使用するFASシステムでSAP HANAを運用する際の推奨事項や考慮事項について説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_fas_fc_introduction.html["TR-4384：『SAP HANA on NetApp FAS Systems with Fibre Channel Protocol』"]
ファイバチャネルを使用するFASシステムでSAP HANAを運用する際の推奨事項や考慮事項について説明します。

link:https://www.netapp.com/pdf.html?item=/media/19887-TR-4821.pdf["TR-4821 ：『 SAP HANA on IBM Power Systems and NetApp AFF Systems with NFS 』"^]
IBM Power Systems は、 SAP HANA などの大量のデータを処理するミッションクリティカルなワークロード向けに設計されています。IBM Power Systems は、優れた仮想化と柔軟性、高速なプロビジョニング、手頃な価格の拡張性、最大限のアップタイムという 4 つの主要機能を提供することで、 SAP HANA の導入を簡易化し、高速化します。AFF製品ファミリは、TDI（テーラードデータセンター統合）プロジェクトでSAP HANAとの使用が認定されており、IBM Power Systemsを完全に補完します。このドキュメントでは、ONTAPとAFF製品ファミリーおよびIBM電源システムを使用したNAS（NFS）ストレージのセットアップに関する推奨事項について説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html["TR-4614 ：『 SAP HANA Backup and Recovery with SnapCenter 』"]
SnapCenterは、SAP HANAなどのデータベース向けに、アプリケーションと整合性のあるデータ保護を実現する、拡張性に優れたユニファイドプラットフォームです。SnapCenter では一元的な管理と監視が可能ですが、一方で、アプリケーション固有のバックアップ、リストア、クローニングのジョブの管理を各ユーザに委譲することができます。SnapCenter を使用すれば、データベース管理者やストレージ管理者は、さまざまなアプリケーションやデータベースのバックアップ、リストア、クローニングの処理を 1 つのツールで管理できます。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/amazon-fsx-overview.html["TR-4926：『SAP HANA on Amazon FSX for NetApp ONTAP - Backup and Recovery with SnapCenter 』"]
Amazon FSx for NetApp ONTAPおよびSnapCenterでSAP HANAのデータ保護を実現するための推奨プラクティスをご紹介します。SnapCenterの概念、設定の推奨事項、処理のワークフロー（設定、バックアップ処理など）などのトピックが含まれます。 リストア処理とリカバリ処理を実行できます。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["TR-4667：『Automating SAP HANA System copy and clone operations with SnapCenter』"]
SnapCenterストレージのクローニングと、クローニング前処理とクローニング後処理を柔軟に定義できるオプションにより、SAP Basisの管理者は、SAPシステムのコピー、クローニング、更新処理を高速化、自動化できます。詳細はこちら任意のプライマリストレージまたはセカンダリストレージに任意のSnapCenter Snapshotバックアップを選択できるため、論理的破損、ディザスタリカバリテスト、SAP QAシステムの更新など、最も重要なユースケースに対応できます。

link:https://www.netapp.com/pdf.html?item=/media/17030-tr4719.pdf["TR-4719：『SAP HANA system replication backup and recovery with SnapCenter』"^]
SAP HANAシステムレプリケーション環境で、SnapCenterテクノロジとSAP HANAプラグインを使用したバックアップとリカバリについて説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["TR-4667：『Automating SAP HANA system copy and clone operations with SnapCenter』"]
アプリケーションと整合性のあるNetApp Snapshotバックアップをストレージレイヤに作成する機能は、システムコピー処理やシステムクローニング処理の基盤となります。ストレージベースのSnapshotバックアップは、SAP HANA用のNetApp SnapCenter プラグインと、SAP HANAデータベースが提供するインターフェイスを使用して作成します。SnapCenter は、SnapshotバックアップをSAP HANAバックアップカタログに登録して、リストアやリカバリ、クローニング処理に使用できるようにします。

link:https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["TR-4646：『SAP HANA disaster recovery with storage replication』"^]
このドキュメントでは、SAP HANA向けのディザスタリカバリ保護のオプションの概要を説明します。同期および非同期のSnapMirrorストレージレプリケーションに基づく、3サイトのディザスタリカバリ解決策の詳細なセットアップ情報とユースケース概要が含まれています。説明している解決策では、SnapCenterとSAP HANAプラグインを使用してデータベースの整合性を管理しています。

link:https://www.netapp.com/pdf.html?item=/media/17050-tr4711pdf.pdf["TR-4711：『SAP HANA backup and Recovery Using NetApp Storage Systems and Commvault software』"^]
本ドキュメントでは、NetAppおよびCommvault解決策for SAP HANAの設計について説明します。これには、Commvault IntelliSnapスナップショット管理テクノロジとSnapshotテクノロジが含まれます。解決策は、ネットアップストレージと Commvault データ保護スイートを基盤としています。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/lama-ansible-introduction.html["TR-4953：『NetApp SAP Landscape Management Integration using Ansible』"]
SAP Landscape Management（LaMa）を使用すると、SAPシステム管理者は、SAPシステムのエンドツーエンドのクローニング、コピー、更新などのSAPシステム運用を自動化できます。ネットアップは、SAP LaMa対応の各種Ansibleモジュールを搭載しており、SAP LaMaのAutomation Studioを通じて、NetApp SnapshotやFlexCloneなどのテクノロジにアクセスできます。これらのテクノロジを使用することで、SAPシステムのクローニング、コピー、更新の処理を簡易化、高速化できます。この統合は、ネットアップのストレージソリューションをオンプレミスで運用しているお客様や、Amazon Web Services、Microsoft Azure、Google Cloud Platformなどのパブリッククラウドプロバイダでネットアップのストレージサービスを使用しているお客様が利用できます。このドキュメントでは、Ansibleによる自動化を使用して、SAPシステムのコピー、クローニング、更新の処理に対応するネットアップのストレージ機能を利用したSAP LaMaの設定について説明します。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/libelle-sc-overview.html["TR-4929：Libelle SystemCopyによるSAPシステムのコピー処理の自動化"]
Libelle SystemCopyは、完全に自動化されたシステムコピーとランドスケープコピーを作成するフレームワークベースのソフトウェア解決策 です。ボタンを口頭で操作することで、QAおよびテストシステムを新しい本番データで更新できます。Libelle SystemCopyは、従来のすべてのデータベースとオペレーティングシステムをサポートし、すべてのプラットフォームに独自のコピーメカニズムを提供しますが、同時にバックアップ/リストア手順や、NetApp SnapshotコピーやNetApp FlexCloneボリュームなどのストレージツールを統合します。
