---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: data-protection-disaster-recovery.html 
summary: これらのテクニカルレポートには、ONTAPのデータ保護とディザスタリカバリの概要と推奨されるプラクティスが記載されています 
---
= データ保護とディザスタリカバリに関するテクニカルレポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapMirrorは、データファブリック全体にわたる、対費用効果に優れた使いやすいユニファイドレプリケーション解決策です。LAN または WAN 経由でデータを高速で複製します。仮想環境と従来の環境の両方で、Microsoft Exchange、Microsoft SQL Server、Oracleなどのビジネスクリティカルなアプリケーションのデータ可用性を高め、高速なデータレプリケーションを実現できます。1つ以上のONTAPストレージシステムにデータをレプリケートし、セカンダリデータを継続的に更新することで、データを最新の状態に保ち、必要なときにいつでも利用できます。外部レプリケーションサーバは必要ありません。

[NOTE]
====
これらのテクニカルレポートでは、について詳しく説明します link:https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["ONTAPデータ保護とディザスタリカバリ"] 製品ドキュメント

====


== SnapMirror

*非同期SnapMirror *
link:https://www.netapp.com/pdf.html?item=/media/17229-tr4015.pdf["TR-4015：『SnapMirror Asynchronous configuration and best practices』"^]
ボリューム、整合グループ、およびStorage Virtual MachineのSnapMirror Asynchronous（SM-A）レプリケーション（SVMディザスタリカバリ）を設定するための推奨されるプラクティスについて説明します。

link:https://www.netapp.com/pdf.html?item=/media/17064-tr4678.pdf["TR-4678：『Data protection and backup ONTAP FlexGroup volumes』"^]
FlexGroupボリュームに推奨されるデータ保護とバックアップについて説明します。トピックには、Snapshotコピー、SnapMirror、その他のデータ保護ソリューションとバックアップソリューションが含まれます。

* SnapMirror Synchronous *
link:https://www.netapp.com/pdf.html?item=/media/17174-tr4733.pdf["TR-4733：『SnapMirror Synchronous configuration and best practices』"^]
SnapMirror Synchronous（SM-S）レプリケーションを設定するための推奨事項について説明します。

* SnapMirrorによる3つのデータセンターからのDR *
link:https://www.netapp.com/pdf.html?item=/media/19369-tr-4832.pdf["TR-4832：『Three Data Center disaster recovery using NetApp SnapMirror for ONTAP 9.7』"^]
レプリケーションにONTAP SnapMirrorテクノロジを使用した、データセンター3つのディザスタリカバリ構成について説明します。



== SnapMirrorを使用したアプリケーションとインフラ

link:link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/srm/overview.html["TR-4900：『VMware Site Recovery Manager with ONTAP』"]
ONTAPは、2002年に最新のデータセンターに導入されて以来、VMware vSphere環境向けストレージ解決策として業界をリードしてきました。革新的な機能を継続的に追加し、コストを削減しながら管理を簡易化しています。ONTAP 解決策for VMware Site Recovery Manager（SRM）は、業界をリードするVMwareのディザスタリカバリ（DR）ソフトウェアです。このソフトウェアには、導入の合理化、リスクの軽減、継続的な管理の簡素化を実現する最新の製品情報や推奨されるプラクティスが含まれます。
