---
settings:
  name: ONTAP Technical Reports
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAPテクニカルレポート
    url: "/index.html"
  - title: アプリケーションとデータベース
    url: "/apps-dbs.html"
  - title: ビジネス継続性
    url: "/business-continuity.html"
  - title: データ保護とディザスタリカバリ
    url: "/data-protection-disaster-recovery.html"
  - title: FlexCacheボリュームとFlexGroupボリューム
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: ネットワーキング
    url: "/networking.html"
  - title: SAN
    url: "/san.html"
  - title: セキュリティ
    entries:
    - title: 概要
      url: "/security.html"
    - section: ransomware-solutions
    - section: zero-trust
    - section: abac
  - title: セキュリティの強化
    entries:
    - title: 概要
      url: "/security-hardening-guides.html"
    - section: ontap-security-hardening
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: 階層化
    url: "/tiering.html"
  - title: 仮想化
    url: "/virtualization.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
