---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, MFA, best practices, best-practices 
permalink: security-hardening-guides.html 
summary: これらのテクニカルレポートには、NetApp ONTAPおよびその他のONTAP関連製品を強化する方法に関するガイダンスが記載されています。 
---
= セキュリティ強化ガイド
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
これらのテクニカルレポートには、NetApp ONTAPおよび他のNetApp製品を強化する方法に関するガイダンスが記載されています。

[NOTE]
====
これらのテクニカルレポートでは、について詳しく説明します link:https://docs.netapp.com/us-en/ontap/security-encryption/index.html["ONTAPセキュリティとデータ暗号化"] 製品ドキュメント

====


== 硬化ガイド

link:https://www.netapp.com/pdf.html?item=/media/10674-tr4569.pdf["TR-4569：『Security Hardening Guide for NetApp ONTAP』"^]
情報システムの機密性、整合性、可用性に関する規定のセキュリティ目標を組織が達成できるようにNetApp ONTAPを構成する方法について説明します。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-otv-hardening-overview.html["ONTAP Tools for VMwareセキュリティ強化ガイド"]
組織が情報システムの機密性、整合性、可用性に関する所定のセキュリティ目標を達成できるように、VMware vSphere用のONTAPツールを構成する方法について説明します。

link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf["TR-4957：『Security Hardening Guide for NetApp SnapCenter』"^]
組織が情報システムの機密性、整合性、可用性に関する所定のセキュリティ目標を達成できるようにNetApp SnapCenterソフトウェアを構成する方法について説明します。

link:https://www.netapp.com/pdf.html?item=/media/83591-tr-4963.pdf["TR-4963：『Security Hardening Guide：BlueXP Cloud Backup for Applications』"^]
組織が情報システムの機密性、整合性、可用性に関して規定されたセキュリティ目標を達成できるように、NetApp Cloud Backup for Applicationsを構成する方法について説明します。

link:https://netapp.com/pdf.html?item=/media/78654-tr-4943.pdf["TR-4943：『Security Hardening Guide for NetApp Active IQ Unified Manager』"^]
情報システムの機密性、整合性、可用性に関する規定のセキュリティ目標を組織が達成できるようにNetApp Active IQ Unified Managerを構成する方法について説明します。

link:https://www.netapp.com/pdf.html?item=/media/78941-tr-4945.pdf["TR-4945：『Security Hardening Guide for NetApp Manageability SDK』"^]
NetApp Manageability SDK(NMSDK)を構成して、組織が情報システムの機密性、整合性、可用性に関する所定のセキュリティ目標を達成できるようにする方法について説明します。
