---
permalink: zero-trust/zero-trust-cloud-deployments.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, cloud, deployments, hybrid, amazon web services, aws, microsoft azure, google cloud platform, gcp, GCNV, Google Cloud, Google Cloud NetApp Volumes 
summary: NetAppのオプションにより、オンプレミスのデータ管理システムをハイブリッドクラウドに拡張し、業界をリードするクラウドプロバイダはゼロトラストのセキュリティ管理をサポート 
---
= ゼロトラストとハイブリッドクラウド環境
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetAppは、ハイブリッド クラウドのデータに関するオーソリティです。NetApp は、Amazon Web Services (AWS)、Microsoft Azure、Google Cloud、その他の主要なクラウド プロバイダーを使用して、オンプレミスのデータ管理システムをハイブリッド クラウドに拡張するためのさまざまなオプションを提供しています。NetAppのハイブリッド クラウド ソリューションは、オンプレミスのONTAPシステムおよびONTAP Select Software-Defined Storageで採用されているものと同じゼロ トラスト セキュリティ対策に対応しています。

AWS (FSxN)、Google Cloud (GCNV)、および Microsoft Azure 向けAzure NetApp Files向けのエンタープライズ クラスのクラウドネイティブ ファイル サービスを使用することで、一般的な CAPEX 制約なしにパブリック クラウドの容量を簡単に拡張できます。これらは分析やDevOpsなど、データを大量に使用するワークロードに最適なクラウド データ サービスであり、NetAppの柔軟性のあるオンデマンド ストレージ サービスと、ONTAPデータ管理機能をフルマネージド形式で組み合わせて利用できます。

ONTAP は、 NetApp SnapMirrorデータ レプリケーション ソフトウェアを使用して、オンプレミスのONTAPシステムと AWS、Google Cloud、または Azure ストレージ環境間でデータを移動できるようにします。
