---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: 自動化により、組織はゼロトラストの導入を手動の手順にとどまらず拡張して、自動化された不正なアクティビティから防御できます。 
---
= ONTAPの外部にあるNetAppセキュリティの自動化とオーケストレーションの制御
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動化を使用すると、最小限の人間の支援でプロセスや手順を実行できます。自動化により、組織はゼロトラスト環境を手動の手順をはるかに超えて拡張し、自動化された不正なアクティビティから保護できます。

Ansibleは、オープンソースのソフトウェアプロビジョニング、構成管理、およびアプリケーション展開ツールです。このソフトウェアは多くのUnix系システムで動作し、Unix系システムとMicrosoft Windowsの両方を構成できます。システム構成を記述するための独自の宣言型言語が含まれています。AnsibleはMichael DeHaanによって開発され、2015年にRed Hatに買収されました。AnsibleはエージェントレスでありSSHまたはWindows Remote Management（リモートのPowerShell実行を可能にする）を介して一時的にリモート接続し、タスクを実行します。NetAppは https://www.netapp.com/devops/ansible/["ONTAPソフトウェア向け150個のAnsibleモジュール"^]以上を開発しており、Ansible自動化フレームワークとのさらなる統合を実現しています。NetApp向けAnsibleモジュールは、望ましい状態を定義してターゲットのNetApp環境に伝達する方法に関する一連の手順を提供します。モジュールは、ライセンスの設定、アグリゲートやストレージ仮想マシンの作成、ボリュームの作成、スナップショットの復元など、さまざまなタスクをサポートするように構築されています。Ansibleロールは https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["GitHubで公開"^]、NetApp DoD Unified Capabilities （UC） Deployment Guideに特化して作成されています。

利用可能なモジュールのライブラリを使用することで、Ansibleプレイブックを簡単に開発し、独自のアプリケーションやビジネスニーズに合わせてカスタマイズして、日常的なタスクを自動化できます。作成したプレイブックを実行して指定したタスクを実行することで、時間を節約し、生産性を向上させることができます。NetAppでは、サンプルのプレイブックを作成して共有しています。プレイブックは直接使用することも、ニーズに合わせてカスタマイズすることもできます。

Data Infrastructure Insightsは、インフラストラクチャ全体の可視性を提供するインフラストラクチャ監視ツールです。  Data Infrastructure Insightsを使用すると、パブリック クラウド インスタンスやプライベート データ センターを含むすべてのリソースを監視、トラブルシューティング、最適化できます。 Data Infrastructure Insights を使用すると、平均解決時間を 90% 短縮し、クラウドの問題の 80% がエンド ユーザーに影響を与えるのを防ぐことができます。クラウド インフラのコストを平均で33%削減可能なほか、実用的なインテリジェンスによりデータを保護し、内部の脅威に対するリスクも軽減できます。 Data Infrastructure Insightsのストレージ ワークロード セキュリティ機能により、AI と ML を使用したユーザー行動分析が可能になり、内部脅威によって異常なユーザー行動が発生したときに警告を発することができます。ONTAPの場合、Storage Workload Securityではゼロ トラストFPolicyエンジンを使用します。
