---
sidebar: sidebar 
permalink: afx/afx-architecture.html 
keywords: netapp afx, architecture, storage availability zone, nvram, raid, disaggregated 
summary: NetApp AFXは、統合型ONTAPとは大きく異なるアーキテクチャを採用しています。ストレージの提供方法、ノードとディスクの相互作用方法、および容量管理方法において。 
---
= NetApp AFX アーキテクチャと統合 ONTAP の違い
:allow-uri-read: 
:icons: font
:imagesdir: ../media/afx/


[role="lead"]
NetApp AFXは、統合型ONTAPとは大きく異なるアーキテクチャを採用しています。ストレージの提供方法、ノードとディスクの相互作用方法、および容量管理方法において。

以前は、統一されたONTAPアーキテクチャが、直接接続されたHAペアを介してファイル、オブジェクト、およびブロックデータのストレージを提供する方法の全体像を示しました。HAペアはそれぞれ独自のディスクセットを所有し、ディスクの集合体を介して物理容量を提供します。このセクションでは、統合されたONTAPとNetApp AFXアーキテクチャの主な違いについて、さらに詳しく説明します。



[[how-to-tell-if-a-system-is-running-netapp-afx]]
== システムが NetApp AFX を実行しているかどうかを確認する方法

システムが NetApp AFX を実行しているかどうかを確認する主な方法は、次のコマンドを実行することです：

[listing]
----
AFX::> node show -fields personality
node             personality
---------------- -----------
afx-01           AFX
afx-02           AFX
----
もう1つの手がかりは新しいストレージ可用性ゾーンですが、これもまたNetAppオールSANアレイ（ASA）で利用可能な概念です。そのコマンドを使えば、容量を確認できます。

[listing]
----
AFX::> storage availability-zone show
                     Availability Zone Name: storage_availability_zone_0
                     Availability Zone UUID: 545cb59f-32e9-11f1-a2f5-d039eabdd925
                                 Total Size: 69.59TB
                              Physical Used: 837.1GB
                      Physical Used Percent: 1%
                                  Available: 68.77TB
                              Metadata Used: 837.1GB
                  Log and Recovery Metadata: 834.6GB
                              Delayed Frees: 2.50GB
 Physical User Data Without Snapshot Copies: 17.24MB
  Logical User Data Without Snapshot Copies: 17.24MB
   Efficiency Ratio Without Snapshot Copies: 1.00:1
               Space Full Threshold Percent: 98%
        Space Nearly Full Threshold Percent: 95%
----


[[architecture-topics]]
== アーキテクチャのトピック

* link:afx-architecture-node-disk.html["ノードとディスクの関係"]
* link:afx-architecture-capacity-pool.html["単一容量プール"]
* link:afx-architecture-nvram-ha.html["複製された NVRAM および HA フェイルオーバー動作"]
* link:afx-architecture-independent-scale.html["独立した線形スケール"]
* link:afx-architecture-raid.html["RAIDの変更"]
* link:afx-architecture-storage-efficiency.html["Storage Efficiency"]
* link:afx-architecture-feature-support.html["ONTAP機能サポートの変更"]
* link:afx-architecture-flexgroup.html["FlexGroup 管理の改善"]
* link:afx-architecture-volume-moves.html["ボリューム移動"]
* link:afx-architecture-cluster-scale.html["クラスター規模"]
* link:afx-architecture-root-volume.html["ルートボリュームの変更"]


[cols="1,1"]
|===


| link:afx-whats-new.html["前へ"] | link:afx-architecture-node-disk.html["次：ノードとディスクの関係"] 
|===