---
sidebar: sidebar 
permalink: afx/afx-architecture-root-volume.html 
keywords: netapp afx, root volume, boot media, nvme, m.2, cluster database 
summary: NetApp AFX がルートボリュームを仮想化し、ブートイメージとクラスタデータベースをオンボードのブートメディアに移動する方法について説明します。 
---
= ルートボリュームの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/afx/


[role="lead"]
NetApp AFXは物理的なルートアグリゲートを削除し、ブートイメージと複製されたクラスタデータベースにオンボードのNVMeブートメディアを使用します。



[[root-volume-changes]]
== ルートボリュームの変更

NetApp ONTAPでは、各ノードにルートボリュームが割り当てられます。このボリュームは、ログファイル、ブートイメージ、コアファイル、クラスタデータベースなど、システム固有のファイルや機能に使用されます。

統合ONTAPでは、これらのルートボリュームは物理ルートアグリゲート上に存在していました。ルートアグリゲートが使用する容量を削減するため、Advanced Disk Partitioning（ADP）を使用して、データドライブのパーティションをまたいでルートアグリゲートが作成されました。

NetApp AFXは物理アグリゲートを排除するため、ルートアグリゲートやADPを使用する必要がなくなります。ルートボリュームは依然として概念として存在しますが、現在は容量プールの仮想化領域に存在し、追加の設定は不要です。さらに、ルートボリュームの機能も変更されます。ブートイメージと複製されたクラスタデータベースは、ストレージ スタックから移動され、各AFXノードに搭載されているオンボードブートメディアに配置されます。これにより、ストレージ スタックへのアクセスが失われても、ノードは起動してクラスタの適格性を維持できるため、トラブルシューティングの複雑さが軽減されます。



[[onboard-boot-media]]
== オンボード ブート メディア

NetApp AFXノードは、オンボードのブートメディアとして、約3.8TBの容量を持つNVMe接続のM.2デバイスを活用します。これらのブートデバイスには、ストレージエンクロージャとは別にブートイメージファイルと複製されたデータベースが含まれており、ディスクアクセスに問題が発生した場合に冗長性を高めます。ブートメディアに障害が発生した場合、ノードはHAパートナーによって引き継がれ、ブートメディアを交換できます。交換後、新しいONTAPイメージはストレージ管理者によってデバイスにロードされ、ONTAPがクラスタデータベースを自動的に再構築し、完全な機能を復元します。

[cols="1,1"]
|===


| link:afx-architecture-cluster-scale.html["前へ：クラスター規模"] | link:afx-performance.html["次へ：パフォーマンス"] 
|===