---
sidebar: sidebar 
permalink: afx/afx-capabilities.html 
keywords: netapp afx, networking, security, data protection, nondisruptive, volumes 
summary: NetApp AFXは、統合ONTAPと同じネットワークスタック、セキュリティ機能、データ保護テクノロジ、無停止運用、およびボリュームタイプをサポートしますが、いくつかの調整が加えられています。 
---
= ネットワーク、セキュリティ、および運用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/afx/


[role="lead"]
NetApp AFXは、統合ONTAPと同じネットワークスタック、セキュリティ機能、データ保護技術、無停止運用、およびボリュームタイプをサポートしていますが、分散型アーキテクチャ特有の調整がいくつか加えられています。



== ネットワーキング

NetApp AFX のネットワーク スタックは、統合 ONTAP と同一です。

* データLIFは、ネットワークアドレスを内部サービスおよび外部サービスに提示するために依然として使用されています。
* 各ノードには、独自の物理ポートと仮想ポートのセットがあります。
* VLAN、ifgroup、およびBGPはすべて引き続きサポートされています。
* LIFは、クラスタ内の物理ノード間およびポート間でフェイルオーバーを行うことができます。
* IPspace／ブロードキャストドメインの設定は以前と同じです。
* 各SVMは、それぞれ専用のデータネットワークを持つことができます。
* 管理ネットワークはデータネットワークから分離できます。
* クライアントのデータネットワークは、新たに400GBのネットワークサポートが追加された以外は変更されません。
* バックエンドクラスタスイッチは、引き続きNetAppが提供する「ゴールデン構成」ファイルによって構成されます。


ネットワークの主な違いは以下のとおりです：

* バックエンドクラスタのネットワークポートは、クラスタスイッチへの100GB接続のみをサポートするようになりました。
* クラスタスイッチは400GBに対応しているため、バックエンドノード接続には4 x 100GBブレークアウトケーブルを使用して、スイッチで使用するポート数を削減します。
* NVRAMは、スイッチ上の新しいHA VLAN構成を介して、バックエンドクラスタネットワーク全体のHAペア間でミラーリングされるようになりました。
* 新しいDCNネットワークは、AI Data Engineに対してデフォルトで追加されます。これらのIPアドレスは自動的に生成され、必要に応じて変更できます。




== セキュリティ

NetApp AFXはONTAPで動作します。つまり、ONTAPと同じセキュリティを使用しているということです。すべての暗号モジュールは同一であるため、認証プロセスが完了すれば、セキュリティ認証も同一になります。NetApp AFXは、統合ONTAPと同じセキュリティ暗号のサポートを活用しています。

さらに、NetApp AFXは、unified ONTAPが提供する多くのセキュリティ機能をサポートしています（ただし、これらに限定されません）：

* 自律型ランサムウェア対策
* セキュアなマルチテナンシー
* 保存時の暗号化（ボリューム暗号化）および転送時の暗号化（TLS 1.3）
* 自己暗号化ドライブ（SED）
* NFSおよびSMB Kerberos認証と暗号化
* マルチ管理者認証
* SnapLock


統合 ONTAP が取得した認証（およびその他のセキュリティ強化情報）については、以下を参照してください：

* link:https://security.netapp.com/certifications["NetApp製品セキュリティ"^]
* link:https://docs.netapp.com/us-en/ontap-technical-reports/ontap-security-hardening/security-hardening-overview.html["ONTAPセキュリティ強化の概要"^]




== スナップショットとデータ保護

NetApp AFXは、統合型ONTAPと同じスナップショットおよびレプリケーション技術を活用しており、これらの機能の動作方法に大きな変更はありません。実際、AFXは、使い慣れたlink:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["ルールと設定"^]を使用して、統合型ONTAPシステムとの間でレプリケーションを行うことができます。

AFXにおけるレプリケーションの唯一の例外は、FlexGroupボリュームを統合されたONTAPシステムにレプリケートする場合です。その場合、デスティネーションの統合されたONTAPシステムは、Advanced Capacity Balancingサポートを提供するために、ONTAP 9.16.1以降を実行している必要があります。



== ノンストップ オペレーション

ONTAPは、ボリュームの移動、アップグレード、クラスタのメンテナンス、ストレージのフェイルオーバーなど、無停止で運用できる操作を提供します。NetApp AFXは、若干の調整を加えて、同じ無停止運用を提供します。

* ボリュームの移動は引き続き無停止で実行できますが、コピーは不要になりました。
* ストレージのフェイルオーバーは依然としてサービスに支障をきたしませんが、最初のフェイルオーバー後、ボリュームはクラスタ内の生存しているすべてのノード間で再バランスされます。
* LIFの移行は同一です。
* ハードウェアの保守とアップグレードは同一です。




== ボリューム タイプ

統合ONTAPは、以下のような複数のボリュームタイプをサポートしています。

* FlexVol
* FlexGroup ボリューム
* FlexCache
* FlexClone
* オブジェクトバケット


NetApp AFXは、これらの各ボリュームタイプを完全にサポートするだけでなく、ユニファイドONTAPシステムとのFlexCacheボリュームの完全な相互運用性も提供します。

FlexGroup ボリュームが AFX アーキテクチャからどのようなメリットを得られるかについては、link:afx-architecture.html#flexgroup-volume-management-improvements["FlexGroup ボリューム管理の機能拡張"]を参照してください。
